spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: L1ftOff$
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 5mins
    refreshTokenExpiration: 604800 # 7days
stripe:
  secretKey: ${STRIPE_SECRET_KEY}